### ISSUE TITLE
Cannot assign `function|table` to parameter `function`.

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/vscode-openra-lua#9]
![image](https://user-images.githubusercontent.com/756669/221356216-19f6a09a-9553-4d7b-89a8-293d41a53014.png)

**Comment by penev92** [comment]
The issue here is that the base Lua extension - https://marketplace.visualstudio.com/items?itemName=sumneko.lua detects `VehicleProduction`, the function in this script (allies02.lua) and also detects `VehicleProduction`, the table in nod09-AI.lua because it doesn't care what global is in what file. So it decides that `VehicleProduction`'s type is `function|table`.
Probably nothing we can do unless we find a way to limit our mission globals to their own files (maybe via naming conventions?).

**Comment by Mailaender** [comment]
You are right that functions and tables from other files clashed here. Renamed them in https://github.com/OpenRA/OpenRA/pull/20698.
